### ISSUE TITLE
Start bot 

### ISSUE THREAD

**Issue by frafra077** [karthikiyengar/teleshell#1]
after you set it up with my data, how do I start it? I have to give some commands via shell? you can start it automatically when you restart the operating system?

**Comment by karthikiyengar** [comment]
After you've set the token and added your user ID to the whitelist, you can simply run node server.js and start talking to your bot. What problem are you facing?

Take a look at the updated readme to get teleshell working on startup.

**Comment by frafra077** [comment]
I configured everything but as soon as I start from this error

> /home/osmc/teleshell/server.js:7
		var { token, whitelist, processTimeout } = config;
		    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by karthikiyengar** [comment]
Some language features which were being used in the code are not supported by your version of node. 

I've removed them so as to support lower versions too. You can take a pull and try now - it should work. If it doesn't I would appreciate you sharing the errors you receive.

**Comment by frafra077** [comment]
nothing wrong yet, this is the error

/home/osmc/teleshell/server.js:2
let config;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by karthikiyengar** [comment]
Could you please tell me what version of node are you running? `node --version`

**Comment by frafra077** [comment]
node
v4.3.2

**Comment by karthikiyengar** [comment]
Okay, I've made a small change. I've tested it on your version and it should work now.

**Comment by frafra077** [comment]
Now you start :-) But after a few minutes from this error:

Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.197:443
    at new RequestError (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request/request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

**Comment by karthikiyengar** [comment]
This could be due to connectivity problems in trying to reach the Telegram servers. Please open a new issue if this happens too frequently and you're sure that it's not your Internet connection.

**Comment by frafra077** [comment]
ok thanks
