### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by frafra077** [karthikiyengar/teleshell#2]
after a few minutes of this error, the connection is not a problem as everything works properly:

Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.198:443
    at new RequestError (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/osmc/teleshell/node_modules/node-telegram-bot-api/node_modules/request/request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

**Comment by frafra077** [comment]
I made a continuous ping and I never packet losses, but the bot stops

**Comment by karthikiyengar** [comment]
@fraraf85 - Thanks for the inputs, I'll look into it. Maybe the Telegram APIs have a retry method.

**Comment by frafra077** [comment]
I tried another bot that uses node, and not this type of error. the bot is this https://github.com/rEDSAMK/raspberry-telegram-bot
So I think it's a problem programmatically

**Comment by karthikiyengar** [comment]
I've bumped the telegram-api version. The issue you're having seems to be related to https://github.com/yagop/node-telegram-bot-api/issues/170

Let me know if it works for you (pull + npm install), else I can try increasing the polling timeout.

Additionally, I would suggest that you upgrade your version of node - the telegram API will no longer be supporting Node.js v4.x in the future.

You could use the excellent n package to do that: https://github.com/tj/n

**Comment by frafra077** [comment]
thanks now works correctly. I also upgraded node

**Comment by karthikiyengar** [comment]
@fraraf85 - Glad it works for you :-)
